version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: inventory
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    command: python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/inventory
      - PYTHONPATH=/app
    depends_on:
      - db

  frontend:
    build: ./frontend
    command: python -m streamlit run pages/home.py
    volumes:
      - ./frontend:/app
    ports:
      - "8501:8501"
    environment:
      - PYTHONPATH=/app
    depends_on:
      - backend

volumes:
  postgres_data: